language: node_js

node_js:
 - "0.10"
 - "0.12"



install:
 - npm install

services:

addons:
 postgresql: "9.3"


before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER test WITH UNENCRYPTED PASSWORD 'test' " -U postgres
  - psql testdb -c "CREATE EXTENSION hstore SCHEMA public;" -U postgres




script:
  - export CODECOV_TOKEN="da541dee-74f2-45e3-9d3f-4962fa9e15d0"
  - npm test

